### PR TITLE
Allow direct use of archive URLs in harness attribute

### LINKED ISSUE #70: Make it easier to use a "master" harness version
It would be nice if we could have a way of specifying a master harness version directly in the `workspace.yml` without needing to create a `harnesses.json`.

Old way:

`workspace.yml`:
```yaml
workspace('my-app'):
  description: My application
  harness: inviqa/go:v0.7.0
  overlay: tools/workspace

harness.repository.source('local'): ./tools/harnesses.json
```

`tools/harnesses.json`:
```json
{
  "inviqa/go": {
     "v0.7.0": {
      "type": "tar.gz",
      "url": "https://github.com/inviqa/harness-go/archive/master.tar.gz"
     }
  }
}
```

A simplified way could be something like 

`workspace.yml`:
```yaml
workspace('my-app'):
  description: My application
  harness: inviqa/go:master
  overlay: tools/workspace
```

I appreciate this would mean that workspace itself would need to parse the `master` tag, and have awareness of the GitHub archive URLs, and this may not be acceptable.

### PR DESCRIPTION
**Pull request by jameshalsall**
Currently, harness definitions have to be updated in https://my127.io/workspace/harnesses.json. It was discussed in #70 that it would be nicer to be able to just specify your harness archive URL directly in the `workspace.yml` of your project, without needing the additional local harnesses manifest. For example

```
workspace('go-sample'):
  description: generated local workspace for go-sample.
  harness: https://github.com/inviqa/harness-go/archive/master.tar.gz
```

This PR makes that possible, however, it is just a first pass to get some feedback. I noticed there are unused getters/properties on the `Package` class which I've marked deprecated too.

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
does this also work with `ws create myproject https://github.com/inviqa/harness-go/archive/master.tar.gz`?

**Comment by jameshalsall** [comment]
I haven't tested it, but in theory it should. I will try that

**Comment by jameshalsall** [comment]
I have no reason to believe the `ws create ...` won't work, right now it will create the project directory and the correct harness value in its `workspace.yml`, but then tries to execute my host `ws` utility which doesn't support that harness format yet, but `cd`ing into that directory and running a `ws install` with this build works fine.

**Comment by kierenevans** [comment]
I've rebased on top of the PHP 8.0 work :)

**Review by andytson-inviqa — APPROVED** [review]

**Pull request merged**
